"""Document/state store port — persistence for projects, conversations,
messages, papers, documents, chunks and agent memory.

Backed by DynamoDB (single table) in production; an in-memory implementation
is used in tests.
"""
from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from mentis.domain.models import (
    Chunk,
    Conversation,
    Document,
    Message,
    Paper,
    Project,
)


@runtime_checkable
class DocStorePort(Protocol):
    # --- projects ---
    async def get_or_create_project(self, name: str) -> Project: ...

    # --- conversations ---
    async def get_conversation(self, conversation_id: str) -> Optional[Conversation]: ...
    async def create_conversation(self, project_id: str) -> Conversation: ...
    async def add_message(self, conversation_id: str, message: Message) -> None: ...
    async def get_messages(self, conversation_id: str, *, limit: int = 20) -> list[Message]: ...

    # --- papers ---
    async def upsert_paper(self, project_id: str, paper: Paper) -> bool:
        """Insert a paper; return True if newly inserted, False if it already existed."""
        ...
    async def paper_exists(self, project_id: str, dedup_key: str) -> bool: ...
    async def search_papers(self, project_id: str, query: str, *, limit: int = 25) -> list[Paper]: ...

    # --- documents & chunks ---
    async def upsert_document(self, document: Document) -> None: ...
    async def get_document(self, document_id: str) -> Optional[Document]: ...
    async def list_documents(self, *, limit: int = 100) -> list[Document]: ...
    async def add_chunks(self, chunks: list[Chunk]) -> None: ...
    async def get_chunk(self, document_id: str, chunk_id: str) -> Optional[Chunk]: ...

    # --- agent memory ---
    async def add_memory(self, project_id: str, agent: str, key: Optional[str], content: str) -> None: ...
    async def recent_memory(self, project_id: str, agent: str, *, limit: int = 5) -> list[str]: ...
    async def memory_key_exists(self, project_id: str, agent: str, key: str) -> bool: ...
