from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class ObjectStorePort(Protocol):
    async def put_bytes(self, key: str, data: bytes, *, content_type: str = "application/octet-stream") -> str: ...
    async def get_bytes(self, key: str) -> bytes: ...
    async def exists(self, key: str) -> bool: ...
    def presigned_put_url(self, key: str, *, expires: int = 3600, content_type: str = "application/pdf") -> str: ...
